create table dolibardev.llx_expensereport_det
(
    rowid                   int auto_increment
        primary key,
    fk_expensereport        int                              not null,
    docnumber               varchar(128)                     null,
    fk_c_type_fees          int                              not null,
    fk_projet               int                              null,
    comments                text                             not null,
    product_type            int           default -1         null,
    qty                     double                           not null,
    subprice                double(24, 8) default 0.00000000 not null,
    value_unit              double(24, 8)                    not null,
    remise_percent          double                           null,
    tva_tx                  double(6, 3)                     null,
    localtax1_tx            double(6, 3)  default 0.000      null,
    localtax1_type          varchar(10)                      null,
    localtax2_tx            double(6, 3)  default 0.000      null,
    localtax2_type          varchar(10)                      null,
    total_ht                double(24, 8) default 0.00000000 not null,
    total_tva               double(24, 8) default 0.00000000 not null,
    total_localtax1         double(24, 8) default 0.00000000 null,
    total_localtax2         double(24, 8) default 0.00000000 null,
    total_ttc               double(24, 8) default 0.00000000 not null,
    date                    date                             not null,
    info_bits               int           default 0          null,
    special_code            int           default 0          null,
    rang                    int           default 0          null,
    import_key              varchar(14)                      null,
    fk_multicurrency        int                              null,
    multicurrency_code      varchar(3)                       null,
    multicurrency_subprice  double(24, 8) default 0.00000000 null,
    multicurrency_total_ht  double(24, 8) default 0.00000000 null,
    multicurrency_total_tva double(24, 8) default 0.00000000 null,
    multicurrency_total_ttc double(24, 8) default 0.00000000 null,
    fk_facture              int           default 0          null,
    fk_code_ventilation     int           default 0          null,
    vat_src_code            varchar(10)   default ''         null,
    rule_warning_message    text                             null,
    fk_c_exp_tax_cat        int                              null,
    fk_ecm_files            int                              null
)
    charset = latin1;

