create table llx_supplier_proposal
(
    rowid                   int auto_increment
        primary key,
    ref                     varchar(30)                             not null,
    entity                  int           default 1                 not null,
    ref_ext                 varchar(255)                            null,
    ref_int                 varchar(255)                            null,
    fk_soc                  int                                     null,
    fk_projet               int                                     null,
    tms                     timestamp     default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP,
    datec                   datetime                                null,
    date_valid              datetime                                null,
    date_cloture            datetime                                null,
    fk_user_author          int                                     null,
    fk_user_modif           int                                     null,
    fk_user_valid           int                                     null,
    fk_user_cloture         int                                     null,
    fk_statut               smallint      default 0                 not null,
    price                   double        default 0                 null,
    remise_percent          double        default 0                 null,
    remise_absolue          double        default 0                 null,
    remise                  double        default 0                 null,
    total_ht                double(24, 8) default 0.00000000        null,
    total_tva               double(24, 8) default 0.00000000        null,
    localtax1               double(24, 8) default 0.00000000        null,
    localtax2               double(24, 8) default 0.00000000        null,
    total_ttc               double(24, 8) default 0.00000000        null,
    fk_account              int                                     null,
    fk_currency             varchar(3)                              null,
    fk_cond_reglement       int                                     null,
    fk_mode_reglement       int                                     null,
    note_private            text                                    null,
    note_public             text                                    null,
    model_pdf               varchar(255)                            null,
    last_main_doc           varchar(255)                            null,
    date_livraison          date                                    null,
    fk_shipping_method      int                                     null,
    import_key              varchar(14)                             null,
    extraparams             varchar(255)                            null,
    fk_multicurrency        int                                     null,
    multicurrency_code      varchar(3)                              null,
    multicurrency_tx        double(24, 8) default 1.00000000        null,
    multicurrency_total_ht  double(24, 8) default 0.00000000        null,
    multicurrency_total_tva double(24, 8) default 0.00000000        null,
    multicurrency_total_ttc double(24, 8) default 0.00000000        null
)
    engine = InnoDB;

