create table llx_fichinterdet_rec
(
    rowid                        int auto_increment
        primary key,
    fk_fichinter                 int                              not null,
    date                         datetime                         null,
    description                  text                             null,
    duree                        int                              null,
    rang                         int           default 0          null,
    total_ht                     double(24, 8)                    null,
    subprice                     double(24, 8)                    null,
    fk_parent_line               int                              null,
    fk_product                   int                              null,
    label                        varchar(255)                     null,
    tva_tx                       double(6, 3)                     null,
    localtax1_tx                 double(6, 3)  default 0.000      null,
    localtax1_type               varchar(1)                       null,
    localtax2_tx                 double(6, 3)  default 0.000      null,
    localtax2_type               varchar(1)                       null,
    qty                          double                           null,
    remise_percent               double        default 0          null,
    remise                       double        default 0          null,
    fk_remise_except             int                              null,
    price                        double(24, 8)                    null,
    total_tva                    double(24, 8)                    null,
    total_localtax1              double(24, 8) default 0.00000000 null,
    total_localtax2              double(24, 8) default 0.00000000 null,
    total_ttc                    double(24, 8)                    null,
    product_type                 int           default 0          null,
    date_start                   datetime                         null,
    date_end                     datetime                         null,
    info_bits                    int           default 0          null,
    buy_price_ht                 double(24, 8) default 0.00000000 null,
    fk_product_fournisseur_price int                              null,
    fk_code_ventilation          int           default 0          not null,
    fk_export_commpta            int           default 0          not null,
    special_code                 int unsigned  default 0          null,
    fk_unit                      int                              null,
    import_key                   varchar(14)                      null
)
    engine = InnoDB;

