create table llx_user
(
    rowid                        int auto_increment
        primary key,
    entity                       int       default 1                 not null,
    ref_employee                 varchar(50)                         null,
    ref_ext                      varchar(50)                         null,
    admin                        smallint  default 0                 null,
    employee                     tinyint   default 1                 null,
    fk_establishment             int       default 0                 null,
    datec                        datetime                            null,
    tms                          timestamp default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP,
    fk_user_creat                int                                 null,
    fk_user_modif                int                                 null,
    login                        varchar(50)                         not null,
    pass_encoding                varchar(24)                         null,
    pass                         varchar(128)                        null,
    pass_crypted                 varchar(128)                        null,
    pass_temp                    varchar(128)                        null,
    api_key                      varchar(128)                        null,
    gender                       varchar(10)                         null,
    civility                     varchar(6)                          null,
    lastname                     varchar(50)                         null,
    firstname                    varchar(50)                         null,
    address                      varchar(255)                        null,
    zip                          varchar(25)                         null,
    town                         varchar(50)                         null,
    fk_state                     int       default 0                 null,
    fk_country                   int       default 0                 null,
    birth                        date                                null,
    job                          varchar(128)                        null,
    office_phone                 varchar(20)                         null,
    office_fax                   varchar(20)                         null,
    user_mobile                  varchar(20)                         null,
    personal_mobile              varchar(20)                         null,
    email                        varchar(255)                        null,
    personal_email               varchar(255)                        null,
    signature                    text                                null,
    socialnetworks               text                                null,
    fk_soc                       int                                 null,
    fk_socpeople                 int                                 null,
    fk_member                    int                                 null,
    fk_user                      int                                 null,
    fk_user_expense_validator    int                                 null,
    fk_user_holiday_validator    int                                 null,
    idpers1                      varchar(128)                        null,
    idpers2                      varchar(128)                        null,
    idpers3                      varchar(128)                        null,
    note_public                  text                                null,
    note                         text                                null,
    model_pdf                    varchar(255)                        null,
    datelastlogin                datetime                            null,
    datepreviouslogin            datetime                            null,
    datelastpassvalidation       datetime                            null,
    datestartvalidity            datetime                            null,
    dateendvalidity              datetime                            null,
    iplastlogin                  varchar(250)                        null,
    ippreviouslogin              varchar(250)                        null,
    egroupware_id                int                                 null,
    ldap_sid                     varchar(255)                        null,
    openid                       varchar(255)                        null,
    statut                       tinyint   default 1                 null,
    photo                        varchar(255)                        null,
    lang                         varchar(6)                          null,
    color                        varchar(6)                          null,
    barcode                      varchar(255)                        null,
    fk_barcode_type              int       default 0                 null,
    accountancy_code             varchar(32)                         null,
    nb_holiday                   int       default 0                 null,
    thm                          double(24, 8)                       null,
    tjm                          double(24, 8)                       null,
    salary                       double(24, 8)                       null,
    salaryextra                  double(24, 8)                       null,
    dateemployment               date                                null,
    dateemploymentend            date                                null,
    weeklyhours                  double(16, 8)                       null,
    import_key                   varchar(14)                         null,
    default_range                int                                 null,
    default_c_exp_tax_cat        int                                 null,
    national_registration_number varchar(50)                         null,
    fk_warehouse                 int                                 null,
    constraint uk_user_api_key
        unique (api_key),
    constraint uk_user_fk_member
        unique (fk_member),
    constraint uk_user_fk_socpeople
        unique (fk_socpeople),
    constraint uk_user_login
        unique (login, entity)
)
    engine = InnoDB;

create index idx_user_fk_societe
    on llx_user (fk_soc);

